---
- name: "Check cramfs disabled"
  stat:
    path: "/etc/modprobe.d/60-blacklist_fs-cramfs.conf"
  register: cramfsExists
- debug:
          var: cramfsExists.stat.exists
# - name: Write log file cramfs
#   lineinfile:
#      line: "{{ ansible_default_ipv4.address }}|Filesystem Configuration|Ensure mounting of cramfs filesystems is disabled|{{ cramfsExists.stat.exists }}|"
#      insertafter: EOF
#      dest: "{{ path_file_pre_check }}/{{ filename_checked }}"
#   delegate_to: 127.0.0.1
  # local_action: lineinfile line={{ cramfsExists }} path=/home/ec2-user/log/pre-checked.txt
# - name: "Do something if path exists"
#   command: ...
#   when: result.stat.exists
# - name: "Config cramfs disabled"
#   shell: "echo blacklist cramfs > /etc/modprobe.d/60-blacklist_fs-cramfs.conf"
#   when: not cramfsExists.stat.exists
- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_default_ipv4.address }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Filesystem Configuration"
    task_number_control_hardening: "1.1"
    task_control_hardening: "Ensure mounting of cramfs filesystems is disabled"
    result_flag: "{{ cramfsExists.stat.exists }}"
    remark: "Test Log file reuse"