# - name: Copy SQL files
#    win_copy: 
#      src: "../templates/2.4-database-mail-xps-config-config-set-0-checked.sql"
#      dest: "C:\\2.4-database-mail-xps-config-config-set-0-checked.sql"
#    register: db_sql_copyfile_state
#  - name: Task2.4
#    win_command: "sqlcmd -S {{ db_server | default(ansible_hostname, true) }} 
#    -i {{ db_artifact_dest_dir }}\\2.4-database-mail-xps-config-config-set-0-checked.sql"
#    register: sql_command

- name: 2.4 Ensure 'Database Mail XPs' Server Configuration Option is set to '0'   
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT name,
    CAST(value as int) as value_configured,
    CAST(value_in_use as int) as value_in_use
  FROM sys.configurations
  WHERE name = 'Database Mail XPs';\" | Select-Object * -ExcludeProperty ItemArray, Table, RowError, RowState, HasErrors | ConvertTo-Json"
  register: database_mail_xps_config_set_0_checked

- set_fact:
    ids: "{{ database_mail_xps_config_set_0_checked.stdout|from_json}}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.name
- debug:
        var: ids.value_configured
- debug:
        var: ids.value_in_use
- name: Check Condition
  set_fact:
    resultCheckConfigurationOption: "{{ ids.value_configured == '0' }}"
- debug:
        var: resultCheckConfigurationOption
- debug:
        var: ansible_ip_addresses[0]
- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "2.4"
    task_control_hardening: "Ensure 'Database Mail XPs' Server Configuration Option is set to '0'"
    result_flag: "{{ resultCheckConfigurationOption }}"
    remark: ""