# - name: Copy SQL files
#    win_copy: 
#      src: "../templates/2.9-trustworthy-database-property-set-0-checked.sql"
#      dest: "C:\\2.9-trustworthy-database-property-set-0-checked.sql"
#    register: db_sql_copyfile_state
#  - name: Task1
#    win_command: "sqlcmd -S {{ db_server | default(ansible_hostname, true) }} 
#    -i {{ db_artifact_dest_dir }}\\2.9-trustworthy-database-property-set-0-checked.sql"
#    register: sql_command

- name: 2.9 Ensure 'Trustworthy' Database Property is set to 'Off'   
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT name
        FROM sys.databases
        WHERE is_trustworthy_on = 1
        AND name != 'msdb';\" "
  register: trustworthy_database_property_set_off_checked

- set_fact:
    ids: "{{ trustworthy_database_property_set_off_checked }}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.name
# - debug:
#         var: ids.value_configured
# - debug:
#         var: ids.SP_installed
- name: Check Condition
  set_fact:
    resultCheckDatabaseProperty: "{{ ids.stdout is none }}"
- debug:
        var: resultCheckDatabaseProperty
- debug:
        var: ansible_ip_addresses[0]
- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "2.9"
    task_control_hardening: "Ensure 'Trustworthy' Database Property is set to 'Off'"
    result_flag: "{{ resultCheckDatabaseProperty }}"
    remark: ""